apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firstpvc
  namespace: wp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
  selector:
    matchLabels:
      pv: local    
  dataSourceRef:
    namespace: default
  storageClassName: hostpath