apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpresspv
  namespace: wp
  labels:
    pv: local2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/disks/pv2
