apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpresspvc
  namespace: wp
  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
  selector:
    matchLabels:
      pv: local2   
  dataSourceRef:
    namespace: default
  storageClassName: hostpath